env:
  browser: false
  node: true

extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'plugin:@ianwremmel/ianwremmel/react'
  - 'plugin:@ianwremmel/ianwremmel/typescript'
  - 'plugin:storybook/recommended'
  - 'prettier'

overrides:
  # make sure eslint lints all files
  - files:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'

  - files:
      - src/**
    env:
      browser: true

  - files:
      - '**/*.jsx'
      - '**/*.tsx'
    rules:
      'react/jsx-uses-react': 'off'
      'react/react-in-jsx-scope': 'off'

settings:
  react:
    version: 'detect'

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: ['!src/**/*']
  import/no-unresolved:
    - error
    - ignore:
        - \.(scss|less|css)$
