env:
  browser: false
  node: true

extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'plugin:@ianwremmel/ianwremmel/react'
  - 'prettier'

overrides:
  # make sure eslint lints all files
  - files:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'

  - files:
      - src/**
    env:
      browser: true

  - files:
      - '**/*.ts'
      - '**/*.tsx'
    extends:
      - 'plugin:@ianwremmel/ianwremmel/typescript'
    rules:
      no-use-before-define: off
      '@typescript-eslint/no-use-before-define':
        - error
        - classes: true
          functions: false
          variables: true
  - files:
      - '**/*.stories.*'
    rules:
      require-jsdoc: off

parserOptions:
  sourceType: 'script'

settings:
  react:
    version: 'detect'

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: ['!src/**/*']
  no-restricted-syntax: off
  import/no-unresolved:
    - error
    - ignore:
        - \.(scss|less|css)$
