env:
  browser: false
  node: true

extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'plugin:@ianwremmel/ianwremmel/react'
  - 'prettier'

overrides:
  - files:
      - src/**
    env:
      browser: true

parserOptions:
  sourceType: 'script'

settings:
  react:
    version: 'detect'

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: ['!src/**/*']
  no-restricted-syntax: off
