on: push
name: Untrusted Workflow
jobs:
  fixup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ianwremmel/prevent-fixup-commits@v1.0.2

  nopush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ianwremmel/prevent-nopush-commits@v1.0.3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run lint
        env:
          ESLINT_FORMAT_OPTIONS: '--format json-with-metadata --output-file reports/style/eslint.json'
          TSC_OPTIONS: '| tee reports/style/tsc.log'
      - uses: check-run-reporter/action@v2.0.0
        if: ${{ always() }}
        with:
          token: '62f20048-075b-4fef-b858-e16790015077'
          label: ESLint
          report: 'reports/style/eslint.json'
      - uses: check-run-reporter/action@v2.0.0
        if: ${{ always() }}
        with:
          token: '62f20048-075b-4fef-b858-e16790015077'
          label: TSC
          report: 'reports/style/tsc.log'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm test
      - uses: check-run-reporter/action@v2.0.0
        if: ${{ always() }}
        with:
          token: '62f20048-075b-4fef-b858-e16790015077'
          label: Unit Tests
          report: 'reports/junit/**/*.xml'
